# Generated by Django 4.2.1 on 2023-06-19 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_alter_course_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='credit',
            new_name='marks',
        ),
    ]
